---
version: '3.1'
services:
  lib-react-gpt:
    build: .
    image: meliuz/lib-react-gpt:development
    networks:
      - meliuz
    volumes:
      - .:/app
      - /app/node_modules

networks:
  meliuz:
    external: true
